src/main/java/com/jyp/justplan/domain/BaseEntity.java
=> feat: jus-37 BaseEntity 생성

src/main/java/com/jyp/justplan/domain/BaseEntity.java, src/main/java/com/jyp/justplan/domain/memo/application/MemoService.java, src/main/java/com/jyp/justplan/domain/memo/domain/Memo.java, src/main/java/com/jyp/justplan/domain/memo/domain/MemoRepository.java, src/main/java/com/jyp/justplan/domain/memo/dto/request/MemoRequestDto.java, src/main/java/com/jyp/justplan/domain/memo/dto/response/MemoResponseDto.java, src/main/java/com/jyp/justplan/domain/memo/exception/NoSuchMemoException.java, src/main/java/com/jyp/justplan/domain/memo/presentation/MemoController.java
=> feat: jus-37 메모-crud-구현

src/main/java/com/jyp/justplan/domain/memo/application/MemoService.java, src/main/java/com/jyp/justplan/domain/memo/domain/Memo.java, src/main/java/com/jyp/justplan/domain/memo/dto/request/MemoRequestDto.java, src/main/java/com/jyp/justplan/domain/memo/dto/response/MemoResponseDto.java
=> feat: jus-37 메모-color-추가

src/main/java/com/jyp/justplan/config/OAuthSecurityConfig.java
=> fix: cors 헤더 추가

src/main/java/com/jyp/justplan/domain/plan/application/PlanService.java, src/main/java/com/jyp/justplan/domain/plan/domain/Plan.java, src/main/java/com/jyp/justplan/domain/plan/domain/tag/TagRepository.java, src/main/java/com/jyp/justplan/domain/plan/dto/request/PlanCreateRequest.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanDetailResponse.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanResponse.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlansResponse.java, src/main/java/com/jyp/justplan/domain/plan/exception/tag/NoSuchTagException.java, src/main/java/com/jyp/justplan/domain/plan/presentation/PlanController.java, src/test/java/com/jyp/justplan/domain/plan/application/PlanServiceTest.java, src/test/java/com/jyp/justplan/domain/plan/domain/PlanRepositoryTest.java, src/test/java/com/jyp/justplan/domain/plan/domain/PlanTest.java, src/test/java/com/jyp/justplan/domain/plan/domain/tag/PlanTagRepositoryTest.java, src/test/java/com/jyp/justplan/domain/plan/presentation/PlanControllerTest.java
**일정 지역 연동**
- Plan - City 연동
- 변경에 따른 테스트코드 수정
**전체 일정 응답 변경**
- 페이지 수 등의 기타 정보를 포함한 응답으로 변경
=> feat: jus-29 일정 지역 연동과 전체 일정 응답 변경

src/main/java/com/jyp/justplan/domain/plan/application/PlanService.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanResponse.java
**전체 일정 응답 변경**
- Budget 정보 추가 (총 예산)
- n박 n일 정보 추가
**일정 세부 응답 변경**
- useExpense에 무관하게 expense 정보 전송
=> feat: jus-56 전체 일정 응답, 일정 세부 응답 변경

src/main/java/com/jyp/justplan/domain/city/application/CityService.java, src/main/java/com/jyp/justplan/domain/city/domain/CityRepository.java, src/main/java/com/jyp/justplan/domain/city/exception/CitySearchException.java, src/main/java/com/jyp/justplan/domain/city/presentation/CityController.java
=> feat: jus-59-도시 검색

src/main/java/com/jyp/justplan/config/SwaggerConfig.java
=> feat: jus-67-swaggger 설정 변경

src/main/java/com/jyp/justplan/domain/place/application/GooglePlaceService.java, src/main/java/com/jyp/justplan/domain/place/domain/GoogleMapType.java, src/main/java/com/jyp/justplan/domain/place/domain/GooglePlace.java, src/main/java/com/jyp/justplan/domain/place/domain/GooglePlaceRepository.java, src/main/java/com/jyp/justplan/domain/place/domain/Place.java, src/main/java/com/jyp/justplan/domain/place/dto/request/GooglePlaceRequest.java, src/main/java/com/jyp/justplan/domain/place/dto/response/GooglePlaceResponse.java, src/main/java/com/jyp/justplan/domain/place/dto/response/PlaceResponse.java, src/main/java/com/jyp/justplan/domain/place/presentation/GooglePlaceController.java
=> Feature/jus 68 장소 검색구현

src/main/java/com/jyp/justplan/domain/plan/application/PlanService.java, src/main/java/com/jyp/justplan/domain/plan/application/UserPlanService.java, src/main/java/com/jyp/justplan/domain/plan/domain/PlanRepository.java, src/main/java/com/jyp/justplan/domain/plan/domain/UserPlan.java, src/main/java/com/jyp/justplan/domain/plan/domain/UserPlanRepository.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/Scrap.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/ScrapRepository.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/ScrapStore.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/ScrapStoreImpl.java, src/main/java/com/jyp/justplan/domain/plan/dto/request/PlanIdRequest.java, src/main/java/com/jyp/justplan/domain/plan/dto/request/PlanScrapRequest.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanDetailResponse.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanResponse.java, src/main/java/com/jyp/justplan/domain/plan/exception/scrap/NoSuchScrapException.java, src/main/java/com/jyp/justplan/domain/plan/presentation/PlanController.java
**스크랩 기능 구현**
- 특정 일정 스크랩 기능 구현
- 일정 응답에 스크랩 수 포함
- 로그인 한 유저가 스크랩 한 게시글 조회
**자신의 일정 조회 구현**
- 자신이 소속된 일정 조회
=> feature/jus-66 스크랩 기능 구현

src/main/java/com/jyp/justplan/domain/plan/application/PlanService.java, src/main/java/com/jyp/justplan/domain/plan/application/UserPlanService.java, src/main/java/com/jyp/justplan/domain/plan/domain/PlanRepository.java, src/main/java/com/jyp/justplan/domain/plan/domain/UserPlan.java, src/main/java/com/jyp/justplan/domain/plan/domain/UserPlanRepository.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/Scrap.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/ScrapRepository.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/ScrapStore.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/ScrapStoreImpl.java, src/main/java/com/jyp/justplan/domain/plan/dto/request/PlanIdRequest.java, src/main/java/com/jyp/justplan/domain/plan/dto/request/PlanScrapRequest.java, src/main/java/com/jyp/justplan/domain/plan/dto/request/PlanUpdateRequest.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/OriginPlanResponse.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanDetailResponse.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanResponse.java, src/main/java/com/jyp/justplan/domain/plan/exception/scrap/NoSuchScrapException.java, src/main/java/com/jyp/justplan/domain/plan/presentation/PlanController.java
**일정 API 수정**
- Origin Plan Response 수정 (정보 축소)
- 일정 전체 조회 필터링 구현 (지역, MBTI)
- 지출 Request 오류 수정
=> feature/jus-69 일정 API 수정

src/main/java/com/jyp/justplan/domain/place/application/PlaceService.java, src/main/java/com/jyp/justplan/domain/place/domain/Memo.java, src/main/java/com/jyp/justplan/domain/place/domain/Place.java, src/main/java/com/jyp/justplan/domain/place/dto/request/PlaceListRequest.java, src/main/java/com/jyp/justplan/domain/place/dto/request/PlaceRequest.java, src/main/java/com/jyp/justplan/domain/place/presentation/PlaceController.java
장소 생성
- 입력값이 null 구글 장소는 새로 생성
- null이 아니면 기존의 구글 장소와 연결
- 메모 생성 후 장소와 연결
=> feat: jus-73 장소 생성

src/main/java/com/jyp/justplan/domain/place/application/PlaceService.java, src/main/java/com/jyp/justplan/domain/place/domain/PlaceRepository.java, src/main/java/com/jyp/justplan/domain/place/dto/response/DayPlacesResponse.java, src/main/java/com/jyp/justplan/domain/place/dto/response/MemoResponse.java, src/main/java/com/jyp/justplan/domain/place/dto/response/PlaceResponse.java, src/main/java/com/jyp/justplan/domain/place/dto/response/SchedulePlacesResponse.java, src/main/java/com/jyp/justplan/domain/place/presentation/GooglePlaceController.java, src/main/java/com/jyp/justplan/domain/place/presentation/MemoController.java, src/main/java/com/jyp/justplan/domain/place/presentation/PlaceController.java
일정에 대한 전체 장소 조회기능 구현
- day별로 장소 조회
- orderNum 순서대로 조회되도록 구현
=> feat: jus-74 전체 장소 조회 구현

src/main/java/com/jyp/justplan/domain/place/application/PlaceService.java, src/main/java/com/jyp/justplan/domain/place/dto/response/SchedulePlacesResponse.java, src/main/java/com/jyp/justplan/domain/place/presentation/PlaceController.java
=> feat: jus-74 응답 map으로 수정

src/main/java/com/jyp/justplan/domain/plan/application/PlanService.java, src/main/java/com/jyp/justplan/domain/plan/application/UserPlanService.java, src/main/java/com/jyp/justplan/domain/plan/domain/Plan.java, src/main/java/com/jyp/justplan/domain/plan/domain/PlanRepository.java, src/main/java/com/jyp/justplan/domain/plan/domain/UserPlan.java, src/main/java/com/jyp/justplan/domain/plan/domain/UserPlanRepository.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/ScrapRepository.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanWithAccountBookResponse.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlansResponse.java, src/main/java/com/jyp/justplan/domain/plan/presentation/PlanController.java
**일정 가계부 포함 응답 구현**
- 마이페이지 내 가계부 조회 시 호출하는 API 구현
**일정 전체 조회 스크랩 순 구현**
- 일정 전체 조회 시, 기존 최신순 조회에서 스크랩 많은 순 조회로 수정
=> feat: jus-77 일정 전체 조회 스크랩 순 구현

src/main/java/com/jyp/justplan/domain/place/application/GooglePlaceService.java, src/main/java/com/jyp/justplan/domain/place/application/PlaceService.java, src/main/java/com/jyp/justplan/domain/place/dto/response/PlaceDetailResponse.java
=> feat: jus-79 장소 상세 조회에서 사진 레퍼런스 추가

src/main/java/com/jyp/justplan/domain/place/domain/GooglePlaceStore.java, src/main/java/com/jyp/justplan/domain/place/domain/PlaceRepository.java, src/main/java/com/jyp/justplan/domain/place/domain/PlaceStore.java, src/main/java/com/jyp/justplan/domain/plan/application/PlanService.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanDetailResponse.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanResponse.java
- 일정의 대표 사진(장소 중 하나 랜덤하게 선택) 구현
- 응답 시 포함하도록 수정
=> feat: jus-83 일정 사진 포함 응답 수정

src/main/java/com/jyp/justplan/domain/plan/dto/response/UserPlanResponse.java
=> feat: jus-85 일정 응답에 프로필 사진 포함

src/main/java/com/jyp/justplan/domain/plan/application/PlanService.java
=> feat: jus-87 일정 전체 조회 시 MBTI 검증 로직 추가

src/main/java/com/jyp/justplan/domain/plan/application/PlanService.java, src/main/java/com/jyp/justplan/domain/plan/application/ScrapStore.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/ScrapRepository.java, src/main/java/com/jyp/justplan/domain/plan/domain/scrap/ScrapStoreImpl.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanDetailResponse.java, src/main/java/com/jyp/justplan/domain/plan/dto/response/PlanResponse.java, src/main/java/com/jyp/justplan/domain/plan/presentation/PlanController.java, src/test/java/com/jyp/justplan/domain/plan/application/PlanServiceTest.java
- 일정 응답에 스크랩 여부 포함
- 스크랩 시 응답 반환
=> feat: jus-88 일정 응답에 스크랩 여부 포함
